const fs = require('fs');
const files = {
  'components/design/PremiumButton.tsx': `import {Button} from '@heroui/button';\nexport default function PremiumButton(props: any) { return <Button color="primary" variant="shadow" {...props}/>; }`,
  'components/design/PremiumInput.tsx': `import {Input} from '@heroui/input';\nexport default function PremiumInput(props: any) { return <Input variant="bordered" classNames={{inputWrapper('bg-default-100 hover:bg-default-200'}} {...props}/>; }`,
  'components/design/PremiumCard.tsx': `import {Card, CardBody} from '@heroui/card';\nexport default function PremiumCard({children, className, ...props}: any) { return <Card className={\"border-none bg-background/60 dark:bg-default-100/50 backdrop-blur-lg \" + (className||'')} shadow="sm" {...props}><CardBody>{children}</CardBody></Card>; }`,
  'components/design/PremiumWidget.tsx': `import {Card, CardHeader, CardBody} from '@heroui/card';\nexport default function PremiumWidget({title, subtitle, children, className, ...props}: any) { return <Card className={\"bg-background/60 dark:bg-default-100/50 backdrop-blur-md \" + (className||'')} {...props}>{title&&<CardHeader className=\"flex flex-col items-start px-4 pt-4 pb-0\"><p className=\"text-tiny uppercase font-bold text-primary\">{subtitle}</p><h4 className=\"font-bold text-large\">{title}</h4></CardHeader>}<CardBody>{children}</CardBody></Card>; }`,
  'components/design/Card.tsx': `import {Card as NextUICard, CardBody} from '@heroui/card';\nexport default function Card({children, className, ...props}: any) { return <NextUICard className={className} {...props}><CardBody>{children}</CardBody></NextUICard>; }`,
  'components/design/Section.tsx': `export default function Section({children, className, ...props}: any) { return <section className={\"py-8 \" + (className||'')} {...props}>{children}</section>; }`,
  'components/layout/Container.tsx': `export default function Container({children, className, ...props}: any) { return <div className={\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 \" + (className||'')} {...props}>{children}</div>; }`,
  'components/design/AppAvatar.tsx': `import {Avatar} from '@heroui/avatar';\nexport default function AppAvatar(props: any) { return <Avatar isBordered color="primary" {...props}/>; }`,
  'components/design/StatusBadge.tsx': `import {Chip} from '@heroui/chip';\nexport default function StatusBadge({status, ...props}: any) { const color = status==='active' ? 'success' : status==='inactive' ? 'default' : 'warning'; return <Chip color-tycolor:coloring any status, ...props}>{status}</Chip>; }`,
  'components/design/ListItem.tsx': `export default function ListItem({title, description, left, right, className, onClick, ...props}: any) { return <div onClick={onClick} className={\"flex items-center justify-between p-3 rounded-xl hover:bg-default-100 cursor-pointer transition-colors \" + (className||'')} {...props}><div className=\"flex items-center gap-3\">{left}<div><p className=\"text-sm font-medium\">{title}</p>{description&&<p className=\"text-xs text-default-500\">{description}</p>}</div></div>{right&&<div>{right}</div>}</div>; }`,
  'components/layout/AppLayout.tsx': `export default function AppLayout({ sidebar, topbar, rightPanel, children }: any) { return <div className="bg-background min-h-screen w-full flex"><aside className="hidden lg:flex flex-col w-64 h-screen fixed left-0 top-0 border-r border-divider bg-background z-30">{sidebar}</aside><div className="flex-1 lg:ml-64 flex flex-col min-h-screen"><header className="sticky top-0 z-20 bg-background/80 backdrop-blur-md border-b border-divider">{topbar}</header><main className="flex-1 flex"><div className="flex-1 p-4 lg:p-6 overflow-x-hidden">{children}</div>{rightPanel && <aside className="hidden xl:block w-80 border-l border-divider p-4">{rightPanel}</aside>}</main></div></div>; }`,
  'components/layout/Sidebar.tsx': `import {ScrollShadow} from '@heroui/scroll-shadow';\nexport default function Sidebar({children, className}: any) { return <ScrollShadow className={\"h-full py-6 px-4 \" + (className||'')}>{children}</ScrollShadow>; }`,
  'components/layout/Topbar.tsx': `import {Navbar, NavbarContent} from '@heroui/navbar';\nexport default function Topbar({children, className}: any) { return <Navbar maxWidth="full" className={className} classNames={{wrapper: \"px-4\"}}><NavbarContent justify=\"end\">{children}</NavbarContent></Navbar>; }`
};
for (const [file, content] of Object.entries(files)) {
  fs.writeFileSync(file, content);
}
console.log('Stubs replaced successfully!');